<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CurrenciesSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('currencies')->insert([
            ['codigo_iso' => 'EUR', 'nombre' => 'Euro', 'nombre_en' => 'Euro', 'simbolo' => '€', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'USD', 'nombre' => 'Dólar estadounidense', 'nombre_en' => 'Dólar estadounidense', 'simbolo' => '$', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'JPY', 'nombre' => 'Yen japonés', 'nombre_en' => 'Yen japonés', 'simbolo' => '¥', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'GBP', 'nombre' => 'Libra esterlina', 'nombre_en' => 'Libra esterlina', 'simbolo' => '£', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'AUD', 'nombre' => 'Dólar australiano', 'nombre_en' => 'Dólar australiano', 'simbolo' => 'A$', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'CAD', 'nombre' => 'Dólar canadiense', 'nombre_en' => 'Dólar canadiense', 'simbolo' => 'C$', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'CHF', 'nombre' => 'Franco suizo', 'nombre_en' => 'Franco suizo', 'simbolo' => 'CHF', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'CNY', 'nombre' => 'Yuan chino', 'nombre_en' => 'Yuan chino', 'simbolo' => '¥', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'SEK', 'nombre' => 'Corona sueca', 'nombre_en' => 'Corona sueca', 'simbolo' => 'kr', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'MXN', 'nombre' => 'Peso mexicano', 'nombre_en' => 'Peso mexicano', 'simbolo' => '$', 'created_at' => $now, 'updated_at' => $now, 'alt_usr' => 1, 'mod_usr' => 1],
            ['codigo_iso' => 'AOA', 'nombre' => 'Kwanza angoleño', 'nombre_en' => 'Kwanza angoleño', 'simbolo' => 'Kz', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'DZD', 'nombre' => 'Dinar argelino', 'nombre_en' => 'Dinar argelino', 'simbolo' => 'د.ج', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'XOF', 'nombre' => 'Franco CFA BCEAO', 'nombre_en' => 'Franco CFA BCEAO', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BWP', 'nombre' => 'Pula botsuano', 'nombre_en' => 'Pula botsuano', 'simbolo' => 'P', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BIF', 'nombre' => 'Franco burundés', 'nombre_en' => 'Franco burundés', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'CVE', 'nombre' => 'Escudo caboverdiano', 'nombre_en' => 'Escudo caboverdiano', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'XAF', 'nombre' => 'Franco CFA BEAC', 'nombre_en' => 'Franco CFA BEAC', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KMF', 'nombre' => 'Franco comorense', 'nombre_en' => 'Franco comorense', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'EGP', 'nombre' => 'Libra egipcia', 'nombre_en' => 'Libra egipcia', 'simbolo' => '£', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ERN', 'nombre' => 'Nakfa eritreo', 'nombre_en' => 'Nakfa eritreo', 'simbolo' => 'Nfk', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ETB', 'nombre' => 'Birr etíope', 'nombre_en' => 'Birr etíope', 'simbolo' => 'Br', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'GMD', 'nombre' => 'Dalasi gambiano', 'nombre_en' => 'Dalasi gambiano', 'simbolo' => 'D', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'GHS', 'nombre' => 'Cedi ghanés', 'nombre_en' => 'Cedi ghanés', 'simbolo' => '₵', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'GNF', 'nombre' => 'Franco guineano', 'nombre_en' => 'Franco guineano', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KES', 'nombre' => 'Chelín keniano', 'nombre_en' => 'Chelín keniano', 'simbolo' => 'Sh', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'LSL', 'nombre' => 'Loti lesotense', 'nombre_en' => 'Loti lesotense', 'simbolo' => 'L', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'LRD', 'nombre' => 'Dólar liberiano', 'nombre_en' => 'Dólar liberiano', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'LYD', 'nombre' => 'Dinar libio', 'nombre_en' => 'Dinar libio', 'simbolo' => 'ل.د', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MGA', 'nombre' => 'Ariary malgache', 'nombre_en' => 'Ariary malgache', 'simbolo' => 'Ar', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MWK', 'nombre' => 'Kwacha malauí', 'nombre_en' => 'Kwacha malauí', 'simbolo' => 'MK', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MAD', 'nombre' => 'Dírham marroquí', 'nombre_en' => 'Dírham marroquí', 'simbolo' => 'د.م.', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MUR', 'nombre' => 'Rupia mauriciana', 'nombre_en' => 'Rupia mauriciana', 'simbolo' => '₨', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MRU', 'nombre' => 'Ouguiya mauritano', 'nombre_en' => 'Ouguiya mauritano', 'simbolo' => 'UM', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MZN', 'nombre' => 'Metical mozambiqueño', 'nombre_en' => 'Metical mozambiqueño', 'simbolo' => 'MT', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'NGN', 'nombre' => 'Naira nigeriano', 'nombre_en' => 'Naira nigeriano', 'simbolo' => '₦', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'CDF', 'nombre' => 'Franco congoleño', 'nombre_en' => 'Franco congoleño', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'RWF', 'nombre' => 'Franco ruandés', 'nombre_en' => 'Franco ruandés', 'simbolo' => 'Fr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'STN', 'nombre' => 'Dobra santotomense', 'nombre_en' => 'Dobra santotomense', 'simbolo' => 'Db', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SCR', 'nombre' => 'Rupia seychellense', 'nombre_en' => 'Rupia seychellense', 'simbolo' => '₨', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SLL', 'nombre' => 'Leona sierraleonesa', 'nombre_en' => 'Leona sierraleonesa', 'simbolo' => 'Le', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SOS', 'nombre' => 'Chelín somalí', 'nombre_en' => 'Chelín somalí', 'simbolo' => 'Sh', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ZAR', 'nombre' => 'Rand sudafricano', 'nombre_en' => 'Rand sudafricano', 'simbolo' => 'R', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SDG', 'nombre' => 'Libra sudanesa', 'nombre_en' => 'Libra sudanesa', 'simbolo' => '£', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TZS', 'nombre' => 'Chelín tanzano', 'nombre_en' => 'Chelín tanzano', 'simbolo' => 'Sh', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TND', 'nombre' => 'Dinar tunecino', 'nombre_en' => 'Dinar tunecino', 'simbolo' => 'د.ت', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'UGX', 'nombre' => 'Chelín ugandés', 'nombre_en' => 'Chelín ugandés', 'simbolo' => 'Sh', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'DJF', 'nombre' => 'Franco yibutiano', 'nombre_en' => 'Franco yibutiano', 'simbolo' => 'Fdj', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ZMW', 'nombre' => 'Kwacha zambiano', 'nombre_en' => 'Kwacha zambiano', 'simbolo' => 'ZK', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ZWL', 'nombre' => 'Dólar zimbabuense', 'nombre_en' => 'Dólar zimbabuense', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ARS', 'nombre' => 'Peso argentino', 'nombre_en' => 'Peso argentino', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BSD', 'nombre' => 'Dólar bahameño', 'nombre_en' => 'Dólar bahameño', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BZD', 'nombre' => 'Dólar beliceño', 'nombre_en' => 'Dólar beliceño', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BOB', 'nombre' => 'Boliviano', 'nombre_en' => 'Boliviano', 'simbolo' => 'Bs.', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BRL', 'nombre' => 'Real brasileño', 'nombre_en' => 'Real brasileño', 'simbolo' => 'R$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'CLP', 'nombre' => 'Peso chileno', 'nombre_en' => 'Peso chileno', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'COP', 'nombre' => 'Peso colombiano', 'nombre_en' => 'Peso colombiano', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'CRC', 'nombre' => 'Colón costarricense', 'nombre_en' => 'Colón costarricense', 'simbolo' => '₡', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'CUP', 'nombre' => 'Peso cubano', 'nombre_en' => 'Peso cubano', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'XCD', 'nombre' => 'Dólar del Caribe Oriental', 'nombre_en' => 'Dólar del Caribe Oriental', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'GTQ', 'nombre' => 'Quetzal guatemalteco', 'nombre_en' => 'Quetzal guatemalteco', 'simbolo' => 'Q', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'GYD', 'nombre' => 'Dólar guyanés', 'nombre_en' => 'Dólar guyanés', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'HTG', 'nombre' => 'Gourde haitiano', 'nombre_en' => 'Gourde haitiano', 'simbolo' => 'G', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'HNL', 'nombre' => 'Lempira hondureña', 'nombre_en' => 'Lempira hondureña', 'simbolo' => 'L', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'JMD', 'nombre' => 'Dólar jamaiquino', 'nombre_en' => 'Dólar jamaiquino', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'NIO', 'nombre' => 'Córdoba nicaragüense', 'nombre_en' => 'Córdoba nicaragüense', 'simbolo' => 'C$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PAB', 'nombre' => 'Balboa panameño', 'nombre_en' => 'Balboa panameño', 'simbolo' => 'B/.', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PYG', 'nombre' => 'Guaraní paraguayo', 'nombre_en' => 'Guaraní paraguayo', 'simbolo' => '₲', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PEN', 'nombre' => 'Sol peruano', 'nombre_en' => 'Sol peruano', 'simbolo' => 'S/', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'DOP', 'nombre' => 'Peso dominicano', 'nombre_en' => 'Peso dominicano', 'simbolo' => 'RD$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SRD', 'nombre' => 'Dólar surinamés', 'nombre_en' => 'Dólar surinamés', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TTD', 'nombre' => 'Dólar de Trinidad y Tobago', 'nombre_en' => 'Dólar de Trinidad y Tobago', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'UYU', 'nombre' => 'Peso uruguayo', 'nombre_en' => 'Peso uruguayo', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'VES', 'nombre' => 'Bolívar venezolano', 'nombre_en' => 'Bolívar venezolano', 'simbolo' => 'Bs', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'AFN', 'nombre' => 'Afgani afgano', 'nombre_en' => 'Afgani afgano', 'simbolo' => '؋', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SAR', 'nombre' => 'Riyal saudí', 'nombre_en' => 'Riyal saudí', 'simbolo' => '﷼', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'AMD', 'nombre' => 'Dram armenio', 'nombre_en' => 'Dram armenio', 'simbolo' => '֏', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'AZN', 'nombre' => 'Manat azerí', 'nombre_en' => 'Manat azerí', 'simbolo' => '₼', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BDT', 'nombre' => 'Taka bangladesí', 'nombre_en' => 'Taka bangladesí', 'simbolo' => '৳', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MMK', 'nombre' => 'Kyat birmano', 'nombre_en' => 'Kyat birmano', 'simbolo' => 'Ks', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BND', 'nombre' => 'Dólar de Brunéi', 'nombre_en' => 'Dólar de Brunéi', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KHR', 'nombre' => 'Riel camboyano', 'nombre_en' => 'Riel camboyano', 'simbolo' => '៛', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KRW', 'nombre' => 'Won surcoreano', 'nombre_en' => 'Won surcoreano', 'simbolo' => '₩', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'AED', 'nombre' => 'Dirham de EAU', 'nombre_en' => 'Dirham de EAU', 'simbolo' => 'د.إ', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PHP', 'nombre' => 'Peso filipino', 'nombre_en' => 'Peso filipino', 'simbolo' => '₱', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'GEL', 'nombre' => 'Lari georgiano', 'nombre_en' => 'Lari georgiano', 'simbolo' => '₾', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'INR', 'nombre' => 'Rupia india', 'nombre_en' => 'Rupia india', 'simbolo' => '₹', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'IDR', 'nombre' => 'Rupia indonesia', 'nombre_en' => 'Rupia indonesia', 'simbolo' => 'Rp', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'IQD', 'nombre' => 'Dinar iraquí', 'nombre_en' => 'Dinar iraquí', 'simbolo' => 'ع.د', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'IRR', 'nombre' => 'Rial iraní', 'nombre_en' => 'Rial iraní', 'simbolo' => '﷼', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MVR', 'nombre' => 'Rufiyaa maldiva', 'nombre_en' => 'Rufiyaa maldiva', 'simbolo' => 'ރ', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ILS', 'nombre' => 'Nuevo séquel israelí', 'nombre_en' => 'Nuevo séquel israelí', 'simbolo' => '₪', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'JOD', 'nombre' => 'Dinar jordano', 'nombre_en' => 'Dinar jordano', 'simbolo' => 'د.ا', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KZT', 'nombre' => 'Tenge kazajo', 'nombre_en' => 'Tenge kazajo', 'simbolo' => '₸', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KGS', 'nombre' => 'Som kirguís', 'nombre_en' => 'Som kirguís', 'simbolo' => 'с', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'KWD', 'nombre' => 'Dinar kuwaití', 'nombre_en' => 'Dinar kuwaití', 'simbolo' => 'د.ك', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'LAK', 'nombre' => 'Kip laosiano', 'nombre_en' => 'Kip laosiano', 'simbolo' => '₭', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'LBP', 'nombre' => 'Libra libanesa', 'nombre_en' => 'Libra libanesa', 'simbolo' => 'ل.ل', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MYR', 'nombre' => 'Ringgit malasio', 'nombre_en' => 'Ringgit malasio', 'simbolo' => 'RM', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MNT', 'nombre' => 'Tugrik mongol', 'nombre_en' => 'Tugrik mongol', 'simbolo' => '₮', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'NPR', 'nombre' => 'Rupia nepalí', 'nombre_en' => 'Rupia nepalí', 'simbolo' => '₨', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'OMR', 'nombre' => 'Rial omaní', 'nombre_en' => 'Rial omaní', 'simbolo' => '﷼', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PKR', 'nombre' => 'Rupia pakistaní', 'nombre_en' => 'Rupia pakistaní', 'simbolo' => '₨', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'QAR', 'nombre' => 'Riyal catarí', 'nombre_en' => 'Riyal catarí', 'simbolo' => 'ر.ق', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SGD', 'nombre' => 'Dólar singapurense', 'nombre_en' => 'Dólar singapurense', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SYP', 'nombre' => 'Libra siria', 'nombre_en' => 'Libra siria', 'simbolo' => '£', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'LKR', 'nombre' => 'Rupia de Sri Lanka', 'nombre_en' => 'Rupia de Sri Lanka', 'simbolo' => 'Rs', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'THB', 'nombre' => 'Baht tailandés', 'nombre_en' => 'Baht tailandés', 'simbolo' => '฿', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TWD', 'nombre' => 'Nuevo dólar taiwanés', 'nombre_en' => 'Nuevo dólar taiwanés', 'simbolo' => 'NT$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TJS', 'nombre' => 'Somoni tayiko', 'nombre_en' => 'Somoni tayiko', 'simbolo' => 'ЅМ', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TMT', 'nombre' => 'Manat turcomano', 'nombre_en' => 'Manat turcomano', 'simbolo' => 'm', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TRY', 'nombre' => 'Lira turca', 'nombre_en' => 'Lira turca', 'simbolo' => '₺', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'UZS', 'nombre' => 'Som uzbeko', 'nombre_en' => 'Som uzbeko', 'simbolo' => 'so', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'VND', 'nombre' => 'Dong vietnamita', 'nombre_en' => 'Dong vietnamita', 'simbolo' => '₫', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'YER', 'nombre' => 'Rial yemení', 'nombre_en' => 'Rial yemení', 'simbolo' => '﷼', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ALL', 'nombre' => 'Lek albanés', 'nombre_en' => 'Lek albanés', 'simbolo' => 'L', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BYN', 'nombre' => 'Rublo bielorruso', 'nombre_en' => 'Rublo bielorruso', 'simbolo' => 'Br', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BAM', 'nombre' => 'Marco bosnioherzegovino', 'nombre_en' => 'Marco bosnioherzegovino', 'simbolo' => 'KM', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'BGN', 'nombre' => 'Lev búlgaro', 'nombre_en' => 'Lev búlgaro', 'simbolo' => 'лв', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'HRK', 'nombre' => 'Kuna croata', 'nombre_en' => 'Kuna croata', 'simbolo' => 'kn', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'DKK', 'nombre' => 'Corona danesa', 'nombre_en' => 'Corona danesa', 'simbolo' => 'kr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'HUF', 'nombre' => 'Forinto húngaro', 'nombre_en' => 'Forinto húngaro', 'simbolo' => 'Ft', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'ISK', 'nombre' => 'Corona islandesa', 'nombre_en' => 'Corona islandesa', 'simbolo' => 'kr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'MDL', 'nombre' => 'Leu moldavo', 'nombre_en' => 'Leu moldavo', 'simbolo' => 'L', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'NOK', 'nombre' => 'Corona noruega', 'nombre_en' => 'Corona noruega', 'simbolo' => 'kr', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PLN', 'nombre' => 'Zloty polaco', 'nombre_en' => 'Zloty polaco', 'simbolo' => 'zł', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'CZK', 'nombre' => 'Corona checa', 'nombre_en' => 'Corona checa', 'simbolo' => 'Kč', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'RON', 'nombre' => 'Leu rumano', 'nombre_en' => 'Leu rumano', 'simbolo' => 'lei', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'RUB', 'nombre' => 'Rublo ruso', 'nombre_en' => 'Rublo ruso', 'simbolo' => '₽', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'RSD', 'nombre' => 'Dinar serbio', 'nombre_en' => 'Dinar serbio', 'simbolo' => 'дин', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'UAH', 'nombre' => 'Grivna ucraniana', 'nombre_en' => 'Grivna ucraniana', 'simbolo' => '₴', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'FJD', 'nombre' => 'Dólar fiyiano', 'nombre_en' => 'Dólar fiyiano', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'SBD', 'nombre' => 'Dólar de las Islas Salomón', 'nombre_en' => 'Dólar de las Islas Salomón', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'NZD', 'nombre' => 'Dólar neozelandés', 'nombre_en' => 'Dólar neozelandés', 'simbolo' => '$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'PGK', 'nombre' => 'Kina papú', 'nombre_en' => 'Kina papú', 'simbolo' => 'K', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'WST', 'nombre' => 'Tala samoano', 'nombre_en' => 'Tala samoano', 'simbolo' => 'T', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'TOP', 'nombre' => 'Paʻanga tongano', 'nombre_en' => 'Paʻanga tongano', 'simbolo' => 'T$', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['codigo_iso' => 'VUV', 'nombre' => 'Vatu vanuatuense', 'nombre_en' => 'Vatu vanuatuense', 'simbolo' => 'Vt', 'alt_usr' => 1, 'mod_usr' => 1, 'created_at' => $now, 'updated_at' => $now],
        ]);
        
    }
}