<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PaiSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('pai')->insert([
            [
                'nombre' => 'Chipre',
                'nombre_en' => 'Cyprus',
                'codigo_iso2' => 'CY',
                'codigo_iso3' => 'CYP',
                'codigo_num' => 357,
                'prefijo' => '357',
                'continente' => 3,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Alemania',
                'nombre_en' => 'Germany',
                'codigo_iso2' => 'DE',
                'codigo_iso3' => 'DEU',
                'codigo_num' => 49,
                'prefijo' => '49',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Andorra',
                'nombre_en' => 'Andorra',
                'codigo_iso2' => 'AD',
                'codigo_iso3' => 'AND',
                'codigo_num' => 376,
                'prefijo' => '376',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Austria',
                'nombre_en' => 'Austria',
                'codigo_iso2' => 'AT',
                'codigo_iso3' => 'AUT',
                'codigo_num' => 43,
                'prefijo' => '43',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bélgica',
                'nombre_en' => 'Belgium',
                'codigo_iso2' => 'BE',
                'codigo_iso3' => 'BEL',
                'codigo_num' => 32,
                'prefijo' => '32',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Eslovaquia',
                'nombre_en' => 'Slovakia',
                'codigo_iso2' => 'SK',
                'codigo_iso3' => 'SVK',
                'codigo_num' => 421,
                'prefijo' => '421',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Eslovenia',
                'nombre_en' => 'Slovenia',
                'codigo_iso2' => 'SI',
                'codigo_iso3' => 'SVN',
                'codigo_num' => 386,
                'prefijo' => '386',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'España',
                'nombre_en' => 'Spain',
                'codigo_iso2' => 'ES',
                'codigo_iso3' => 'ESP',
                'codigo_num' => 34,
                'prefijo' => '34',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Estonia',
                'nombre_en' => 'Estonia',
                'codigo_iso2' => 'EE',
                'codigo_iso3' => 'EST',
                'codigo_num' => 372,
                'prefijo' => '372',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Finlandia',
                'nombre_en' => 'Finland',
                'codigo_iso2' => 'FI',
                'codigo_iso3' => 'FIN',
                'codigo_num' => 358,
                'prefijo' => '358',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Francia',
                'nombre_en' => 'France',
                'codigo_iso2' => 'FR',
                'codigo_iso3' => 'FRA',
                'codigo_num' => 33,
                'prefijo' => '33',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Grecia',
                'nombre_en' => 'Greece',
                'codigo_iso2' => 'GR',
                'codigo_iso3' => 'GRC',
                'codigo_num' => 30,
                'prefijo' => '30',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Irlanda',
                'nombre_en' => 'Ireland',
                'codigo_iso2' => 'IE',
                'codigo_iso3' => 'IRL',
                'codigo_num' => 353,
                'prefijo' => '353',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Italia',
                'nombre_en' => 'Italy',
                'codigo_iso2' => 'IT',
                'codigo_iso3' => 'ITA',
                'codigo_num' => 39,
                'prefijo' => '39',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Letonia',
                'nombre_en' => 'Latvia',
                'codigo_iso2' => 'LV',
                'codigo_iso3' => 'LVA',
                'codigo_num' => 371,
                'prefijo' => '371',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Lituania',
                'nombre_en' => 'Lithuania',
                'codigo_iso2' => 'LT',
                'codigo_iso3' => 'LTU',
                'codigo_num' => 370,
                'prefijo' => '370',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Luxemburgo',
                'nombre_en' => 'Luxembourg',
                'codigo_iso2' => 'LU',
                'codigo_iso3' => 'LUX',
                'codigo_num' => 352,
                'prefijo' => '352',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Malta',
                'nombre_en' => 'Malta',
                'codigo_iso2' => 'MT',
                'codigo_iso3' => 'MLT',
                'codigo_num' => 356,
                'prefijo' => '356',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Mónaco',
                'nombre_en' => 'Monaco',
                'codigo_iso2' => 'MC',
                'codigo_iso3' => 'MCO',
                'codigo_num' => 377,
                'prefijo' => '377',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Montenegro',
                'nombre_en' => 'Montenegro',
                'codigo_iso2' => 'ME',
                'codigo_iso3' => 'MNE',
                'codigo_num' => 382,
                'prefijo' => '382',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Países Bajos',
                'nombre_en' => 'Netherlands',
                'codigo_iso2' => 'NL',
                'codigo_iso3' => 'NLD',
                'codigo_num' => 31,
                'prefijo' => '31',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Portugal',
                'nombre_en' => 'Portugal',
                'codigo_iso2' => 'PT',
                'codigo_iso3' => 'PRT',
                'codigo_num' => 351,
                'prefijo' => '351',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'San Marino',
                'nombre_en' => 'San Marino',
                'codigo_iso2' => 'SM',
                'codigo_iso3' => 'SMR',
                'codigo_num' => 378,
                'prefijo' => '378',
                'continente' => 4,
                'moneda' => 1,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Ecuador',
                'nombre_en' => 'Ecuador',
                'codigo_iso2' => 'EC',
                'codigo_iso3' => 'ECU',
                'codigo_num' => 593,
                'prefijo' => '593',
                'continente' => 5,
                'moneda' => 2,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'El Salvador',
                'nombre_en' => 'El Salvador',
                'codigo_iso2' => 'SV',
                'codigo_iso3' => 'SLV',
                'codigo_num' => 503,
                'prefijo' => '503',
                'continente' => 5,
                'moneda' => 2,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Estados Unidos de América',
                'nombre_en' => 'United States of America',
                'codigo_iso2' => 'US',
                'codigo_iso3' => 'USA',
                'codigo_num' => 1,
                'prefijo' => '1',
                'continente' => 5,
                'moneda' => 2,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Timor Oriental',
                'nombre_en' => 'East Timor',
                'codigo_iso2' => 'TL',
                'codigo_iso3' => 'TLS',
                'codigo_num' => 670,
                'prefijo' => '670',
                'continente' => 3,
                'moneda' => 2,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Islas Marshall',
                'nombre_en' => 'Marshall Islands',
                'codigo_iso2' => 'MH',
                'codigo_iso3' => 'MHL',
                'codigo_num' => 692,
                'prefijo' => '692',
                'continente' => 6,
                'moneda' => 2,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Palau',
                'nombre_en' => 'Palau',
                'codigo_iso2' => 'PW',
                'codigo_iso3' => 'PLW',
                'codigo_num' => 680,
                'prefijo' => '680',
                'continente' => 6,
                'moneda' => 2,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Japón',
                'nombre_en' => 'Japan',
                'codigo_iso2' => 'JP',
                'codigo_iso3' => 'JPN',
                'codigo_num' => 81,
                'prefijo' => '81',
                'continente' => 3,
                'moneda' => 3,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Reino Unido',
                'nombre_en' => 'United Kingdom',
                'codigo_iso2' => 'GB',
                'codigo_iso3' => 'GBR',
                'codigo_num' => 44,
                'prefijo' => '44',
                'continente' => 4,
                'moneda' => 4,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Australia',
                'nombre_en' => 'Australia',
                'codigo_iso2' => 'AU',
                'codigo_iso3' => 'AUS',
                'codigo_num' => 61,
                'prefijo' => '61',
                'continente' => 6,
                'moneda' => 5,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Kiribati',
                'nombre_en' => 'Kiribati',
                'codigo_iso2' => 'KI',
                'codigo_iso3' => 'KIR',
                'codigo_num' => 686,
                'prefijo' => '686',
                'continente' => 6,
                'moneda' => 5,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Canadá',
                'nombre_en' => 'Canada',
                'codigo_iso2' => 'CA',
                'codigo_iso3' => 'CAN',
                'codigo_num' => 1,
                'prefijo' => '1',
                'continente' => 5,
                'moneda' => 6,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Suiza',
                'nombre_en' => 'Switzerland',
                'codigo_iso2' => 'CH',
                'codigo_iso3' => 'CHE',
                'codigo_num' => 41,
                'prefijo' => '41',
                'continente' => 4,
                'moneda' => 7,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'China',
                'nombre_en' => 'China',
                'codigo_iso2' => 'CN',
                'codigo_iso3' => 'CHN',
                'codigo_num' => 86,
                'prefijo' => '86',
                'continente' => 3,
                'moneda' => 8,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Suecia',
                'nombre_en' => 'Sweden',
                'codigo_iso2' => 'SE',
                'codigo_iso3' => 'SWE',
                'codigo_num' => 46,
                'prefijo' => '46',
                'continente' => 4,
                'moneda' => 9,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'México',
                'nombre_en' => 'Mexico',
                'codigo_iso2' => 'MX',
                'codigo_iso3' => 'MEX',
                'codigo_num' => 52,
                'prefijo' => '52',
                'continente' => 5,
                'moneda' => 10,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Angola',
                'nombre_en' => 'Angola',
                'codigo_iso2' => 'AO',
                'codigo_iso3' => 'AGO',
                'codigo_num' => 244,
                'prefijo' => '244',
                'continente' => 1,
                'moneda' => 11,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Argelia',
                'nombre_en' => 'Algeria',
                'codigo_iso2' => 'DZ',
                'codigo_iso3' => 'DZA',
                'codigo_num' => 213,
                'prefijo' => '213',
                'continente' => 1,
                'moneda' => 12,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Benín',
                'nombre_en' => 'Benin',
                'codigo_iso2' => 'BJ',
                'codigo_iso3' => 'BEN',
                'codigo_num' => 229,
                'prefijo' => '229',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Botsuana',
                'nombre_en' => 'Botswana',
                'codigo_iso2' => 'BW',
                'codigo_iso3' => 'BWA',
                'codigo_num' => 267,
                'prefijo' => '267',
                'continente' => 1,
                'moneda' => 14,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Burkina Faso',
                'nombre_en' => 'Burkina Faso',
                'codigo_iso2' => 'BF',
                'codigo_iso3' => 'BFA',
                'codigo_num' => 226,
                'prefijo' => '226',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Burundi',
                'nombre_en' => 'Burundi',
                'codigo_iso2' => 'BI',
                'codigo_iso3' => 'BDI',
                'codigo_num' => 257,
                'prefijo' => '257',
                'continente' => 1,
                'moneda' => 15,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Cabo Verde',
                'nombre_en' => 'Cape Verde',
                'codigo_iso2' => 'CV',
                'codigo_iso3' => 'CPV',
                'codigo_num' => 238,
                'prefijo' => '238',
                'continente' => 1,
                'moneda' => 16,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Camerún',
                'nombre_en' => 'Cameroon',
                'codigo_iso2' => 'CM',
                'codigo_iso3' => 'CMR',
                'codigo_num' => 237,
                'prefijo' => '237',
                'continente' => 1,
                'moneda' => 17,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Chad',
                'nombre_en' => 'Chad',
                'codigo_iso2' => 'TD',
                'codigo_iso3' => 'TCD',
                'codigo_num' => 235,
                'prefijo' => '235',
                'continente' => 1,
                'moneda' => 17,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Comoras',
                'nombre_en' => 'Comoros',
                'codigo_iso2' => 'KM',
                'codigo_iso3' => 'COM',
                'codigo_num' => 269,
                'prefijo' => '269',
                'continente' => 1,
                'moneda' => 18,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Egipto',
                'nombre_en' => 'Egypt',
                'codigo_iso2' => 'EG',
                'codigo_iso3' => 'EGY',
                'codigo_num' => 20,
                'prefijo' => '20',
                'continente' => 1,
                'moneda' => 19,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Eritrea',
                'nombre_en' => 'Eritrea',
                'codigo_iso2' => 'ER',
                'codigo_iso3' => 'ERI',
                'codigo_num' => 291,
                'prefijo' => '291',
                'continente' => 1,
                'moneda' => 20,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Etiopía',
                'nombre_en' => 'Ethiopia',
                'codigo_iso2' => 'ET',
                'codigo_iso3' => 'ETH',
                'codigo_num' => 251,
                'prefijo' => '251',
                'continente' => 1,
                'moneda' => 21,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Gabón',
                'nombre_en' => 'Gabon',
                'codigo_iso2' => 'GA',
                'codigo_iso3' => 'GAB',
                'codigo_num' => 241,
                'prefijo' => '241',
                'continente' => 1,
                'moneda' => 17,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Gambia',
                'nombre_en' => 'Gambia',
                'codigo_iso2' => 'GM',
                'codigo_iso3' => 'GMB',
                'codigo_num' => 220,
                'prefijo' => '220',
                'continente' => 1,
                'moneda' => 22,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Ghana',
                'nombre_en' => 'Ghana',
                'codigo_iso2' => 'GH',
                'codigo_iso3' => 'GHA',
                'codigo_num' => 233,
                'prefijo' => '233',
                'continente' => 1,
                'moneda' => 23,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Guinea',
                'nombre_en' => 'Guinea',
                'codigo_iso2' => 'GN',
                'codigo_iso3' => 'GIN',
                'codigo_num' => 224,
                'prefijo' => '224',
                'continente' => 1,
                'moneda' => 24,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Guinea Ecuatorial',
                'nombre_en' => 'Equatorial Guinea',
                'codigo_iso2' => 'GQ',
                'codigo_iso3' => 'GNQ',
                'codigo_num' => 240,
                'prefijo' => '240',
                'continente' => 1,
                'moneda' => 17,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Guinea-Bissau',
                'nombre_en' => 'Guinea-Bissau',
                'codigo_iso2' => 'GW',
                'codigo_iso3' => 'GNB',
                'codigo_num' => 245,
                'prefijo' => '245',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Kenia',
                'nombre_en' => 'Kenya',
                'codigo_iso2' => 'KE',
                'codigo_iso3' => 'KEN',
                'codigo_num' => 254,
                'prefijo' => '254',
                'continente' => 1,
                'moneda' => 25,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Lesoto',
                'nombre_en' => 'Lesotho',
                'codigo_iso2' => 'LS',
                'codigo_iso3' => 'LSO',
                'codigo_num' => 266,
                'prefijo' => '266',
                'continente' => 1,
                'moneda' => 26,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Liberia',
                'nombre_en' => 'Liberia',
                'codigo_iso2' => 'LR',
                'codigo_iso3' => 'LBR',
                'codigo_num' => 231,
                'prefijo' => '231',
                'continente' => 1,
                'moneda' => 27,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Libia',
                'nombre_en' => 'Libya',
                'codigo_iso2' => 'LY',
                'codigo_iso3' => 'LBY',
                'codigo_num' => 218,
                'prefijo' => '218',
                'continente' => 1,
                'moneda' => 28,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Madagascar',
                'nombre_en' => 'Madagascar',
                'codigo_iso2' => 'MG',
                'codigo_iso3' => 'MDG',
                'codigo_num' => 261,
                'prefijo' => '261',
                'continente' => 1,
                'moneda' => 29,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Malawi',
                'nombre_en' => 'Malawi',
                'codigo_iso2' => 'MW',
                'codigo_iso3' => 'MWI',
                'codigo_num' => 265,
                'prefijo' => '265',
                'continente' => 1,
                'moneda' => 30,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Mali',
                'nombre_en' => 'Mali',
                'codigo_iso2' => 'ML',
                'codigo_iso3' => 'MLI',
                'codigo_num' => 223,
                'prefijo' => '223',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Marruecos',
                'nombre_en' => 'Morocco',
                'codigo_iso2' => 'MA',
                'codigo_iso3' => 'MAR',
                'codigo_num' => 212,
                'prefijo' => '212',
                'continente' => 1,
                'moneda' => 31,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Mauricio',
                'nombre_en' => 'Mauritius',
                'codigo_iso2' => 'MU',
                'codigo_iso3' => 'MUS',
                'codigo_num' => 230,
                'prefijo' => '230',
                'continente' => 1,
                'moneda' => 32,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Mauritania',
                'nombre_en' => 'Mauritania',
                'codigo_iso2' => 'MR',
                'codigo_iso3' => 'MRT',
                'codigo_num' => 222,
                'prefijo' => '222',
                'continente' => 1,
                'moneda' => 33,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Mozambique',
                'nombre_en' => 'Mozambique',
                'codigo_iso2' => 'MZ',
                'codigo_iso3' => 'MOZ',
                'codigo_num' => 258,
                'prefijo' => '258',
                'continente' => 1,
                'moneda' => 34,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Niger',
                'nombre_en' => 'Niger',
                'codigo_iso2' => 'NE',
                'codigo_iso3' => 'NER',
                'codigo_num' => 227,
                'prefijo' => '227',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Nigeria',
                'nombre_en' => 'Nigeria',
                'codigo_iso2' => 'NG',
                'codigo_iso3' => 'NGA',
                'codigo_num' => 234,
                'prefijo' => '234',
                'continente' => 1,
                'moneda' => 35,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'República Centroafricana',
                'nombre_en' => 'Central African Republic',
                'codigo_iso2' => 'CF',
                'codigo_iso3' => 'CAF',
                'codigo_num' => 236,
                'prefijo' => '236',
                'continente' => 1,
                'moneda' => 17,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'República del Congo',
                'nombre_en' => 'Republic of the Congo',
                'codigo_iso2' => 'CG',
                'codigo_iso3' => 'COG',
                'codigo_num' => 242,
                'prefijo' => '242',
                'continente' => 1,
                'moneda' => 17,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'República Democrática del Congo',
                'nombre_en' => 'Democratic Republic of the Congo',
                'codigo_iso2' => 'CD',
                'codigo_iso3' => 'COD',
                'codigo_num' => 243,
                'prefijo' => '243',
                'continente' => 1,
                'moneda' => 36,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Ruanda',
                'nombre_en' => 'Rwanda',
                'codigo_iso2' => 'RW',
                'codigo_iso3' => 'RWA',
                'codigo_num' => 250,
                'prefijo' => '250',
                'continente' => 1,
                'moneda' => 37,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Santo Tomé y Príncipe',
                'nombre_en' => 'Sao Tome and Principe',
                'codigo_iso2' => 'ST',
                'codigo_iso3' => 'STP',
                'codigo_num' => 239,
                'prefijo' => '239',
                'continente' => 1,
                'moneda' => 38,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Senegal',
                'nombre_en' => 'Senegal',
                'codigo_iso2' => 'SN',
                'codigo_iso3' => 'SEN',
                'codigo_num' => 221,
                'prefijo' => '221',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Seychelles',
                'nombre_en' => 'Seychelles',
                'codigo_iso2' => 'SC',
                'codigo_iso3' => 'SYC',
                'codigo_num' => 248,
                'prefijo' => '248',
                'continente' => 1,
                'moneda' => 39,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Sierra Leona',
                'nombre_en' => 'Sierra Leone',
                'codigo_iso2' => 'SL',
                'codigo_iso3' => 'SLE',
                'codigo_num' => 232,
                'prefijo' => '232',
                'continente' => 1,
                'moneda' => 40,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Somalia',
                'nombre_en' => 'Somalia',
                'codigo_iso2' => 'SO',
                'codigo_iso3' => 'SOM',
                'codigo_num' => 252,
                'prefijo' => '252',
                'continente' => 1,
                'moneda' => 41,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Sudáfrica',
                'nombre_en' => 'South Africa',
                'codigo_iso2' => 'ZA',
                'codigo_iso3' => 'ZAF',
                'codigo_num' => 27,
                'prefijo' => '27',
                'continente' => 1,
                'moneda' => 42,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Sudán',
                'nombre_en' => 'Sudan',
                'codigo_iso2' => 'SD',
                'codigo_iso3' => 'SDN',
                'codigo_num' => 249,
                'prefijo' => '249',
                'continente' => 1,
                'moneda' => 43,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Tanzania',
                'nombre_en' => 'Tanzania',
                'codigo_iso2' => 'TZ',
                'codigo_iso3' => 'TZA',
                'codigo_num' => 255,
                'prefijo' => '255',
                'continente' => 1,
                'moneda' => 44,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Togo',
                'nombre_en' => 'Togo',
                'codigo_iso2' => 'TG',
                'codigo_iso3' => 'TGO',
                'codigo_num' => 228,
                'prefijo' => '228',
                'continente' => 1,
                'moneda' => 13,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Tunez',
                'nombre_en' => 'Tunisia',
                'codigo_iso2' => 'TN',
                'codigo_iso3' => 'TUN',
                'codigo_num' => 216,
                'prefijo' => '216',
                'continente' => 1,
                'moneda' => 45,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Uganda',
                'nombre_en' => 'Uganda',
                'codigo_iso2' => 'UG',
                'codigo_iso3' => 'UGA',
                'codigo_num' => 256,
                'prefijo' => '256',
                'continente' => 1,
                'moneda' => 46,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Yibuti',
                'nombre_en' => 'Djibouti',
                'codigo_iso2' => 'DJ',
                'codigo_iso3' => 'DJI',
                'codigo_num' => 253,
                'prefijo' => '253',
                'continente' => 1,
                'moneda' => 47,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Zambia',
                'nombre_en' => 'Zambia',
                'codigo_iso2' => 'ZM',
                'codigo_iso3' => 'ZMB',
                'codigo_num' => 260,
                'prefijo' => '260',
                'continente' => 1,
                'moneda' => 48,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Zimbabue',
                'nombre_en' => 'Zimbabwe',
                'codigo_iso2' => 'ZW',
                'codigo_iso3' => 'ZWE',
                'codigo_num' => 263,
                'prefijo' => '263',
                'continente' => 1,
                'moneda' => 49,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Argentina',
                'nombre_en' => 'Argentina',
                'codigo_iso2' => 'AR',
                'codigo_iso3' => 'ARG',
                'codigo_num' => 54,
                'prefijo' => '54',
                'continente' => 5,
                'moneda' => 50,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bahamas',
                'nombre_en' => 'Bahamas',
                'codigo_iso2' => 'BS',
                'codigo_iso3' => 'BHS',
                'codigo_num' => 1242,
                'prefijo' => '1 242',
                'continente' => 5,
                'moneda' => 51,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Belice',
                'nombre_en' => 'Belize',
                'codigo_iso2' => 'BZ',
                'codigo_iso3' => 'BLZ',
                'codigo_num' => 501,
                'prefijo' => '501',
                'continente' => 5,
                'moneda' => 52,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bolivia',
                'nombre_en' => 'Bolivia',
                'codigo_iso2' => 'BO',
                'codigo_iso3' => 'BOL',
                'codigo_num' => 591,
                'prefijo' => '591',
                'continente' => 5,
                'moneda' => 53,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Brasil',
                'nombre_en' => 'Brazil',
                'codigo_iso2' => 'BR',
                'codigo_iso3' => 'BRA',
                'codigo_num' => 55,
                'prefijo' => '55',
                'continente' => 5,
                'moneda' => 54,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Chile',
                'nombre_en' => 'Chile',
                'codigo_iso2' => 'CL',
                'codigo_iso3' => 'CHL',
                'codigo_num' => 56,
                'prefijo' => '56',
                'continente' => 5,
                'moneda' => 55,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Colombia',
                'nombre_en' => 'Colombia',
                'codigo_iso2' => 'CO',
                'codigo_iso3' => 'COL',
                'codigo_num' => 57,
                'prefijo' => '57',
                'continente' => 5,
                'moneda' => 56,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Costa Rica',
                'nombre_en' => 'Costa Rica',
                'codigo_iso2' => 'CR',
                'codigo_iso3' => 'CRI',
                'codigo_num' => 506,
                'prefijo' => '506',
                'continente' => 5,
                'moneda' => 57,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Cuba',
                'nombre_en' => 'Cuba',
                'codigo_iso2' => 'CU',
                'codigo_iso3' => 'CUB',
                'codigo_num' => 53,
                'prefijo' => '53',
                'continente' => 5,
                'moneda' => 58,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Dominica',
                'nombre_en' => 'Dominica',
                'codigo_iso2' => 'DM',
                'codigo_iso3' => 'DMA',
                'codigo_num' => 1767,
                'prefijo' => '1 767',
                'continente' => 5,
                'moneda' => 59,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Granada',
                'nombre_en' => 'Grenada',
                'codigo_iso2' => 'GD',
                'codigo_iso3' => 'GRD',
                'codigo_num' => 1473,
                'prefijo' => '1 473',
                'continente' => 5,
                'moneda' => 59,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Guatemala',
                'nombre_en' => 'Guatemala',
                'codigo_iso2' => 'GT',
                'codigo_iso3' => 'GTM',
                'codigo_num' => 502,
                'prefijo' => '502',
                'continente' => 5,
                'moneda' => 60,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Guyana',
                'nombre_en' => 'Guyana',
                'codigo_iso2' => 'GY',
                'codigo_iso3' => 'GUY',
                'codigo_num' => 592,
                'prefijo' => '592',
                'continente' => 5,
                'moneda' => 61,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Haití',
                'nombre_en' => 'Haiti',
                'codigo_iso2' => 'HT',
                'codigo_iso3' => 'HTI',
                'codigo_num' => 509,
                'prefijo' => '509',
                'continente' => 5,
                'moneda' => 62,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Honduras',
                'nombre_en' => 'Honduras',
                'codigo_iso2' => 'HN',
                'codigo_iso3' => 'HND',
                'codigo_num' => 504,
                'prefijo' => '504',
                'continente' => 5,
                'moneda' => 63,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Jamaica',
                'nombre_en' => 'Jamaica',
                'codigo_iso2' => 'JM',
                'codigo_iso3' => 'JAM',
                'codigo_num' => 1876,
                'prefijo' => '1 876',
                'continente' => 5,
                'moneda' => 64,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Nicaragua',
                'nombre_en' => 'Nicaragua',
                'codigo_iso2' => 'NI',
                'codigo_iso3' => 'NIC',
                'codigo_num' => 505,
                'prefijo' => '505',
                'continente' => 5,
                'moneda' => 65,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Panamá',
                'nombre_en' => 'Panama',
                'codigo_iso2' => 'PA',
                'codigo_iso3' => 'PAN',
                'codigo_num' => 507,
                'prefijo' => '507',
                'continente' => 5,
                'moneda' => 66,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Paraguay',
                'nombre_en' => 'Paraguay',
                'codigo_iso2' => 'PY',
                'codigo_iso3' => 'PRY',
                'codigo_num' => 595,
                'prefijo' => '595',
                'continente' => 5,
                'moneda' => 67,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Perú',
                'nombre_en' => 'Peru',
                'codigo_iso2' => 'PE',
                'codigo_iso3' => 'PER',
                'codigo_num' => 51,
                'prefijo' => '51',
                'continente' => 5,
                'moneda' => 68,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'República Dominicana',
                'nombre_en' => 'Dominican Republic',
                'codigo_iso2' => 'DO',
                'codigo_iso3' => 'DOM',
                'codigo_num' => 1809,
                'prefijo' => '1 809',
                'continente' => 5,
                'moneda' => 69,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'San Cristóbal y Nieves',
                'nombre_en' => 'Saint Kitts and Nevis',
                'codigo_iso2' => 'KN',
                'codigo_iso3' => 'KNA',
                'codigo_num' => 1869,
                'prefijo' => '1 869',
                'continente' => 5,
                'moneda' => 59,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'San Vicente y las Granadinas',
                'nombre_en' => 'Saint Vincent and the Grenadines',
                'codigo_iso2' => 'VC',
                'codigo_iso3' => 'VCT',
                'codigo_num' => 1784,
                'prefijo' => '1 784',
                'continente' => 5,
                'moneda' => 59,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Santa Lucía',
                'nombre_en' => 'Saint Lucia',
                'codigo_iso2' => 'LC',
                'codigo_iso3' => 'LCA',
                'codigo_num' => 1758,
                'prefijo' => '1 758',
                'continente' => 5,
                'moneda' => 59,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Surinám',
                'nombre_en' => 'Suriname',
                'codigo_iso2' => 'SR',
                'codigo_iso3' => 'SUR',
                'codigo_num' => 597,
                'prefijo' => '597',
                'continente' => 5,
                'moneda' => 70,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Trinidad y Tobago',
                'nombre_en' => 'Trinidad and Tobago',
                'codigo_iso2' => 'TT',
                'codigo_iso3' => 'TTO',
                'codigo_num' => 1868,
                'prefijo' => '1 868',
                'continente' => 5,
                'moneda' => 71,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Uruguay',
                'nombre_en' => 'Uruguay',
                'codigo_iso2' => 'UY',
                'codigo_iso3' => 'URY',
                'codigo_num' => 598,
                'prefijo' => '598',
                'continente' => 5,
                'moneda' => 72,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Venezuela',
                'nombre_en' => 'Venezuela',
                'codigo_iso2' => 'VE',
                'codigo_iso3' => 'VEN',
                'codigo_num' => 58,
                'prefijo' => '58',
                'continente' => 5,
                'moneda' => 73,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Afganistán',
                'nombre_en' => 'Afghanistan',
                'codigo_iso2' => 'AF',
                'codigo_iso3' => 'AFG',
                'codigo_num' => 93,
                'prefijo' => '93',
                'continente' => 3,
                'moneda' => 74,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Arabia Saudita',
                'nombre_en' => 'Saudi Arabia',
                'codigo_iso2' => 'SA',
                'codigo_iso3' => 'SAU',
                'codigo_num' => 966,
                'prefijo' => '966',
                'continente' => 3,
                'moneda' => 75,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Armenia',
                'nombre_en' => 'Armenia',
                'codigo_iso2' => 'AM',
                'codigo_iso3' => 'ARM',
                'codigo_num' => 374,
                'prefijo' => '374',
                'continente' => 3,
                'moneda' => 76,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Azerbaiyán',
                'nombre_en' => 'Azerbaijan',
                'codigo_iso2' => 'AZ',
                'codigo_iso3' => 'AZE',
                'codigo_num' => 994,
                'prefijo' => '994',
                'continente' => 3,
                'moneda' => 77,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bangladesh',
                'nombre_en' => 'Bangladesh',
                'codigo_iso2' => 'BD',
                'codigo_iso3' => 'BGD',
                'codigo_num' => 880,
                'prefijo' => '880',
                'continente' => 3,
                'moneda' => 78,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Birmania',
                'nombre_en' => 'Myanmar',
                'codigo_iso2' => 'MM',
                'codigo_iso3' => 'MMR',
                'codigo_num' => 95,
                'prefijo' => '95',
                'continente' => 3,
                'moneda' => 79,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Brunéi',
                'nombre_en' => 'Brunei',
                'codigo_iso2' => 'BN',
                'codigo_iso3' => 'BRN',
                'codigo_num' => 673,
                'prefijo' => '673',
                'continente' => 3,
                'moneda' => 80,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Camboya',
                'nombre_en' => 'Cambodia',
                'codigo_iso2' => 'KH',
                'codigo_iso3' => 'KHM',
                'codigo_num' => 855,
                'prefijo' => '855',
                'continente' => 3,
                'moneda' => 81,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Corea del Sur',
                'nombre_en' => 'South Korea',
                'codigo_iso2' => 'KR',
                'codigo_iso3' => 'KOR',
                'codigo_num' => 82,
                'prefijo' => '82',
                'continente' => 3,
                'moneda' => 82,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Emiratos Árabes Unidos',
                'nombre_en' => 'United Arab Emirates',
                'codigo_iso2' => 'AE',
                'codigo_iso3' => 'ARE',
                'codigo_num' => 971,
                'prefijo' => '971',
                'continente' => 3,
                'moneda' => 83,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Filipinas',
                'nombre_en' => 'Philippines',
                'codigo_iso2' => 'PH',
                'codigo_iso3' => 'PHL',
                'codigo_num' => 63,
                'prefijo' => '63',
                'continente' => 3,
                'moneda' => 84,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Georgia',
                'nombre_en' => 'Georgia',
                'codigo_iso2' => 'GE',
                'codigo_iso3' => 'GEO',
                'codigo_num' => 995,
                'prefijo' => '995',
                'continente' => 3,
                'moneda' => 85,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'India',
                'nombre_en' => 'India',
                'codigo_iso2' => 'IN',
                'codigo_iso3' => 'IND',
                'codigo_num' => 91,
                'prefijo' => '91',
                'continente' => 3,
                'moneda' => 86,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Indonesia',
                'nombre_en' => 'Indonesia',
                'codigo_iso2' => 'ID',
                'codigo_iso3' => 'IDN',
                'codigo_num' => 62,
                'prefijo' => '62',
                'continente' => 3,
                'moneda' => 87,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Irak',
                'nombre_en' => 'Iraq',
                'codigo_iso2' => 'IQ',
                'codigo_iso3' => 'IRQ',
                'codigo_num' => 964,
                'prefijo' => '964',
                'continente' => 3,
                'moneda' => 88,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Irán',
                'nombre_en' => 'Iran',
                'codigo_iso2' => 'IR',
                'codigo_iso3' => 'IRN',
                'codigo_num' => 98,
                'prefijo' => '98',
                'continente' => 3,
                'moneda' => 89,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Islas Maldivas',
                'nombre_en' => 'Maldives',
                'codigo_iso2' => 'MV',
                'codigo_iso3' => 'MDV',
                'codigo_num' => 960,
                'prefijo' => '960',
                'continente' => 3,
                'moneda' => 90,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Israel',
                'nombre_en' => 'Israel',
                'codigo_iso2' => 'IL',
                'codigo_iso3' => 'ISR',
                'codigo_num' => 972,
                'prefijo' => '972',
                'continente' => 3,
                'moneda' => 91,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Jordania',
                'nombre_en' => 'Jordan',
                'codigo_iso2' => 'JO',
                'codigo_iso3' => 'JOR',
                'codigo_num' => 962,
                'prefijo' => '962',
                'continente' => 3,
                'moneda' => 92,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Kazajistán',
                'nombre_en' => 'Kazakhstan',
                'codigo_iso2' => 'KZ',
                'codigo_iso3' => 'KAZ',
                'codigo_num' => 7,
                'prefijo' => '7',
                'continente' => 3,
                'moneda' => 93,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Kirguistán',
                'nombre_en' => 'Kyrgyzstan',
                'codigo_iso2' => 'KG',
                'codigo_iso3' => 'KGZ',
                'codigo_num' => 996,
                'prefijo' => '996',
                'continente' => 3,
                'moneda' => 94,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Kuwait',
                'nombre_en' => 'Kuwait',
                'codigo_iso2' => 'KW',
                'codigo_iso3' => 'KWT',
                'codigo_num' => 965,
                'prefijo' => '965',
                'continente' => 3,
                'moneda' => 95,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Laos',
                'nombre_en' => 'Laos',
                'codigo_iso2' => 'LA',
                'codigo_iso3' => 'LAO',
                'codigo_num' => 856,
                'prefijo' => '856',
                'continente' => 3,
                'moneda' => 96,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Líbano',
                'nombre_en' => 'Lebanon',
                'codigo_iso2' => 'LB',
                'codigo_iso3' => 'LBN',
                'codigo_num' => 961,
                'prefijo' => '961',
                'continente' => 3,
                'moneda' => 97,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Malasia',
                'nombre_en' => 'Malaysia',
                'codigo_iso2' => 'MY',
                'codigo_iso3' => 'MYS',
                'codigo_num' => 60,
                'prefijo' => '60',
                'continente' => 3,
                'moneda' => 98,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Mongolia',
                'nombre_en' => 'Mongolia',
                'codigo_iso2' => 'MN',
                'codigo_iso3' => 'MNG',
                'codigo_num' => 976,
                'prefijo' => '976',
                'continente' => 3,
                'moneda' => 99,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Nepal',
                'nombre_en' => 'Nepal',
                'codigo_iso2' => 'NP',
                'codigo_iso3' => 'NPL',
                'codigo_num' => 977,
                'prefijo' => '977',
                'continente' => 3,
                'moneda' => 100,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Omán',
                'nombre_en' => 'Oman',
                'codigo_iso2' => 'OM',
                'codigo_iso3' => 'OMN',
                'codigo_num' => 968,
                'prefijo' => '968',
                'continente' => 3,
                'moneda' => 101,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Pakistán',
                'nombre_en' => 'Pakistan',
                'codigo_iso2' => 'PK',
                'codigo_iso3' => 'PAK',
                'codigo_num' => 92,
                'prefijo' => '92',
                'continente' => 3,
                'moneda' => 102,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Qatar',
                'nombre_en' => 'Qatar',
                'codigo_iso2' => 'QA',
                'codigo_iso3' => 'QAT',
                'codigo_num' => 974,
                'prefijo' => '974',
                'continente' => 3,
                'moneda' => 103,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Singapur',
                'nombre_en' => 'Singapore',
                'codigo_iso2' => 'SG',
                'codigo_iso3' => 'SGP',
                'codigo_num' => 65,
                'prefijo' => '65',
                'continente' => 3,
                'moneda' => 104,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Siria',
                'nombre_en' => 'Syria',
                'codigo_iso2' => 'SY',
                'codigo_iso3' => 'SYR',
                'codigo_num' => 963,
                'prefijo' => '963',
                'continente' => 3,
                'moneda' => 105,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Sri lanka',
                'nombre_en' => 'Sri Lanka',
                'codigo_iso2' => 'LK',
                'codigo_iso3' => 'LKA',
                'codigo_num' => 94,
                'prefijo' => '94',
                'continente' => 3,
                'moneda' => 106,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Tailandia',
                'nombre_en' => 'Thailand',
                'codigo_iso2' => 'TH',
                'codigo_iso3' => 'THA',
                'codigo_num' => 66,
                'prefijo' => '66',
                'continente' => 3,
                'moneda' => 107,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Taiwán',
                'nombre_en' => 'Taiwan',
                'codigo_iso2' => 'TW',
                'codigo_iso3' => 'TWN',
                'codigo_num' => 886,
                'prefijo' => '886',
                'continente' => 3,
                'moneda' => 108,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Tayikistán',
                'nombre_en' => 'Tajikistan',
                'codigo_iso2' => 'TJ',
                'codigo_iso3' => 'TJK',
                'codigo_num' => 992,
                'prefijo' => '992',
                'continente' => 3,
                'moneda' => 109,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Turkmenistán',
                'nombre_en' => 'Turkmenistan',
                'codigo_iso2' => 'TM',
                'codigo_iso3' => 'TKM',
                'codigo_num' => 993,
                'prefijo' => '993',
                'continente' => 3,
                'moneda' => 110,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Turquía',
                'nombre_en' => 'Turkey',
                'codigo_iso2' => 'TR',
                'codigo_iso3' => 'TUR',
                'codigo_num' => 90,
                'prefijo' => '90',
                'continente' => 3,
                'moneda' => 111,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Uzbekistán',
                'nombre_en' => 'Uzbekistan',
                'codigo_iso2' => 'UZ',
                'codigo_iso3' => 'UZB',
                'codigo_num' => 998,
                'prefijo' => '998',
                'continente' => 3,
                'moneda' => 112,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Vietnam',
                'nombre_en' => 'Vietnam',
                'codigo_iso2' => 'VN',
                'codigo_iso3' => 'VNM',
                'codigo_num' => 84,
                'prefijo' => '84',
                'continente' => 3,
                'moneda' => 113,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Yemen',
                'nombre_en' => 'Yemen',
                'codigo_iso2' => 'YE',
                'codigo_iso3' => 'YEM',
                'codigo_num' => 967,
                'prefijo' => '967',
                'continente' => 3,
                'moneda' => 114,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Albania',
                'nombre_en' => 'Albania',
                'codigo_iso2' => 'AL',
                'codigo_iso3' => 'ALB',
                'codigo_num' => 355,
                'prefijo' => '355',
                'continente' => 4,
                'moneda' => 115,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bielorrusia',
                'nombre_en' => 'Belarus',
                'codigo_iso2' => 'BY',
                'codigo_iso3' => 'BLR',
                'codigo_num' => 375,
                'prefijo' => '375',
                'continente' => 4,
                'moneda' => 116,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bosnia y Herzegovina',
                'nombre_en' => 'Bosnia and Herzegovina',
                'codigo_iso2' => 'BA',
                'codigo_iso3' => 'BIH',
                'codigo_num' => 387,
                'prefijo' => '387',
                'continente' => 4,
                'moneda' => 117,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Bulgaria',
                'nombre_en' => 'Bulgaria',
                'codigo_iso2' => 'BG',
                'codigo_iso3' => 'BGR',
                'codigo_num' => 359,
                'prefijo' => '359',
                'continente' => 4,
                'moneda' => 118,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Croacia',
                'nombre_en' => 'Croatia',
                'codigo_iso2' => 'HR',
                'codigo_iso3' => 'HRV',
                'codigo_num' => 385,
                'prefijo' => '385',
                'continente' => 4,
                'moneda' => 119,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Dinamarca',
                'nombre_en' => 'Denmark',
                'codigo_iso2' => 'DK',
                'codigo_iso3' => 'DNK',
                'codigo_num' => 45,
                'prefijo' => '45',
                'continente' => 4,
                'moneda' => 120,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Hungría',
                'nombre_en' => 'Hungary',
                'codigo_iso2' => 'HU',
                'codigo_iso3' => 'HUN',
                'codigo_num' => 36,
                'prefijo' => '36',
                'continente' => 4,
                'moneda' => 121,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Islandia',
                'nombre_en' => 'Iceland',
                'codigo_iso2' => 'IS',
                'codigo_iso3' => 'ISL',
                'codigo_num' => 354,
                'prefijo' => '354',
                'continente' => 4,
                'moneda' => 122,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Moldavia',
                'nombre_en' => 'Moldova',
                'codigo_iso2' => 'MD',
                'codigo_iso3' => 'MDA',
                'codigo_num' => 373,
                'prefijo' => '373',
                'continente' => 4,
                'moneda' => 123,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Noruega',
                'nombre_en' => 'Norway',
                'codigo_iso2' => 'NO',
                'codigo_iso3' => 'NOR',
                'codigo_num' => 47,
                'prefijo' => '47',
                'continente' => 4,
                'moneda' => 124,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Polonia',
                'nombre_en' => 'Poland',
                'codigo_iso2' => 'PL',
                'codigo_iso3' => 'POL',
                'codigo_num' => 48,
                'prefijo' => '48',
                'continente' => 4,
                'moneda' => 125,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'República Checa',
                'nombre_en' => 'Czech Republic',
                'codigo_iso2' => 'CZ',
                'codigo_iso3' => 'CZE',
                'codigo_num' => 420,
                'prefijo' => '420',
                'continente' => 4,
                'moneda' => 126,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Rumanía',
                'nombre_en' => 'Romania',
                'codigo_iso2' => 'RO',
                'codigo_iso3' => 'ROU',
                'codigo_num' => 40,
                'prefijo' => '40',
                'continente' => 4,
                'moneda' => 127,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Rusia',
                'nombre_en' => 'Russia',
                'codigo_iso2' => 'RU',
                'codigo_iso3' => 'RUS',
                'codigo_num' => 7,
                'prefijo' => '7',
                'continente' => 4,
                'moneda' => 128,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Serbia',
                'nombre_en' => 'Serbia',
                'codigo_iso2' => 'RS',
                'codigo_iso3' => 'SRB',
                'codigo_num' => 381,
                'prefijo' => '381',
                'continente' => 4,
                'moneda' => 129,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Ucrania',
                'nombre_en' => 'Ukraine',
                'codigo_iso2' => 'UA',
                'codigo_iso3' => 'UKR',
                'codigo_num' => 380,
                'prefijo' => '380',
                'continente' => 4,
                'moneda' => 130,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Fiyi',
                'nombre_en' => 'Fiji',
                'codigo_iso2' => 'FJ',
                'codigo_iso3' => 'FJI',
                'codigo_num' => 679,
                'prefijo' => '679',
                'continente' => 6,
                'moneda' => 131,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Islas Salomón',
                'nombre_en' => 'Solomon Islands',
                'codigo_iso2' => 'SB',
                'codigo_iso3' => 'SLB',
                'codigo_num' => 677,
                'prefijo' => '677',
                'continente' => 6,
                'moneda' => 132,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Nueva Zelanda',
                'nombre_en' => 'New Zealand',
                'codigo_iso2' => 'NZ',
                'codigo_iso3' => 'NZL',
                'codigo_num' => 64,
                'prefijo' => '64',
                'continente' => 6,
                'moneda' => 133,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Papúa Nueva Guinea',
                'nombre_en' => 'Papua New Guinea',
                'codigo_iso2' => 'PG',
                'codigo_iso3' => 'PNG',
                'codigo_num' => 675,
                'prefijo' => '675',
                'continente' => 6,
                'moneda' => 134,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Samoa',
                'nombre_en' => 'Samoa',
                'codigo_iso2' => 'WS',
                'codigo_iso3' => 'WSM',
                'codigo_num' => 685,
                'prefijo' => '685',
                'continente' => 6,
                'moneda' => 135,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Tonga',
                'nombre_en' => 'Tonga',
                'codigo_iso2' => 'TO',
                'codigo_iso3' => 'TON',
                'codigo_num' => 676,
                'prefijo' => '676',
                'continente' => 6,
                'moneda' => 136,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ],
            [
                'nombre' => 'Vanuatu',
                'nombre_en' => 'Vanuatu',
                'codigo_iso2' => 'VU',
                'codigo_iso3' => 'VUT',
                'codigo_num' => 678,
                'prefijo' => '678',
                'continente' => 6,
                'moneda' => 137,
                'alt_usr' => 1,
                'mod_usr' => 1,
                'created_at' =>  $now,
                'updated_at' =>  $now,
            ]
        ]);
    }
}
